networks:
  cluster-network:
    driver: bridge

services:
  micro-challenger:
    image: micro-challenger:latest
    hostname: micro-challenger
    networks:
      - cluster-network
    volumes:
      - ./gc25-chall/data:/data
    command: ["0.0.0.0:8866", "/data"]
  
  jobmanager:
    image: flink:latest
    hostname: jobmanager
    container_name: jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    volumes:
      - ./target:/opt/flink/usrlib
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        parallelism.default: 2
    networks:
      - cluster-network

  taskmanager:
    image: flink:latest
    container_name: taskmanager
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    volumes:
      - ./target:/opt/flink/usrlib
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
        parallelism.default: 2
    networks:
      - cluster-network  

  firefox:
    image: jlesage/firefox
    ports:
      - 5800:5800
    networks:
      - cluster-network