networks:
  cluster-network:
    driver: bridge

services:
  micro-challenger:
    image: micro-challenger:latest
    hostname: micro-challenger
    networks:
      - cluster-network
    ports:
      - "8866:8866"
    volumes:
      - ./gc25-chall/data:/data
    command: ["0.0.0.0:8866", "/data"]

  jobmanager:
    build: pyflink
    ports:
      - "8081:8081"
    command: jobmanager
    networks:
      - cluster-network
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    volumes:
      - ./app:/opt/flink/usrlib

  taskmanager:
    build: pyflink
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    networks:
      - cluster-network
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
    volumes:
      - ./app:/opt/flink/usrlib 