networks:
  cluster-network:
    driver: bridge

services:
  micro-challenger:
    image: micro-challenger:latest
    hostname: micro-challenger
    networks:
      - cluster-network
    volumes:
      - ./gc25-chall/data:/data
    command: ["0.0.0.0:8866", "/data"]

  jobmanager:
    build:
      context: ./flink
      dockerfile: Dockerfile
    hostname: jobmanager
    container_name: jobmanager
    cap_add:
    - NET_ADMIN
    command: jobmanager
    volumes:
      - ./target:/opt/flink/usrlib
    env_file:
      - conf/flink.config
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        parallelism.default: 1
    networks:
      - cluster-network

  taskmanager:
    build:
      context: ./flink
      dockerfile: Dockerfile
    depends_on:
      - jobmanager
    cap_add:
    - NET_ADMIN
    command: taskmanager
    volumes:
      - ./target:/opt/flink/usrlib
    env_file:
      - conf/flink.config
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 8
        parallelism.default: 1
    networks:
      - cluster-network

  firefox:
    image: jlesage/firefox
    ports:
      - 5800:5800
    networks:
      - cluster-network