networks:
  cluster-network:
    driver: bridge

services:
  micro-challenger:
    image: micro-challenger:latest
    hostname: micro-challenger
    networks:
      - cluster-network
    volumes:
      - ./gc25-chall/data:/data
    command: ["0.0.0.0:8866", "/data"]

  jobmanager:
    image: flink:latest
    hostname: jobmanager
    container_name: jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    volumes:
      - ./target:/opt/flink/usrlib
      - ./jar/flink-hadoop-fs-2.0.0.jar:/opt/flink/plugins/hdfs/flink-hadoop-fs-2.0.0.jar
    env_file:
      - conf/flink.config
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        parallelism.default: 2
      - USE_EVENT_TIME=true
    networks:
      - cluster-network

  taskmanager:
    image: flink:latest
    container_name: taskmanager
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    volumes:
      - ./target:/opt/flink/usrlib
      - ./jar/flink-hadoop-fs-2.0.0.jar:/opt/flink/plugins/hdfs/flink-hadoop-fs-2.0.0.jar
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
        parallelism.default: 2
        taskmanager.memory.process.size: 4g
      - USE_EVENT_TIME=true

    networks:
      - cluster-network

  firefox:
    image: jlesage/firefox
    ports:
      - 5800:5800
    networks:
      - cluster-network

  namenode:
    build: https://github.com/GentiliEmanuele/docker-hadoop.git
    container_name: namenode
    hostname: namenode
    user: root
    ports:
      - "9870:9870"
      - "54310:54310"
    volumes:
      - ./hdfs_starter/start-master.sh:/opt/scripts/start-master.sh
    entrypoint: /bin/sh
    command: ["/opt/scripts/start-master.sh"]
    networks:
      - cluster-network
    tty: true

  slave1:
    build: https://github.com/GentiliEmanuele/docker-hadoop.git
    container_name: slave1
    hostname: slave1
    ports:
      - "9864:9864"
    volumes:
      - ./hdfs_starter/start-worker.sh:/opt/scripts/start-worker.sh
    entrypoint: /bin/sh
    command: ["/opt/scripts/start-worker.sh"]
    networks:
      - cluster-network
    tty: true

  slave2:
    build: https://github.com/GentiliEmanuele/docker-hadoop.git
    container_name: slave2
    hostname: slave2
    ports:
      - "9865:9864"
    volumes:
      - ./hdfs_starter/start-worker.sh:/opt/scripts/start-worker.sh
    entrypoint: /bin/sh
    command: ["/opt/scripts/start-worker.sh"]
    networks:
      - cluster-network
    tty: true

  slave3:
    build: https://github.com/GentiliEmanuele/docker-hadoop.git
    container_name: slave3
    hostname: slave3
    ports:
      - "9866:9864"
    volumes:
      - ./hdfs_starter/start-worker.sh:/opt/scripts/start-worker.sh
    entrypoint: /bin/sh
    command: ["/opt/scripts/start-worker.sh"]
    networks:
      - cluster-network
    tty: true
