networks:
  cluster-network:
    driver: bridge

services:
  micro-challenger:
    image: micro-challenger:latest
    hostname: micro-challenger
    networks:
      - cluster-network
    volumes:
      - ./gc25-chall/data:/data
    command: ["0.0.0.0:8866", "/data"]

  kafka:
    image: 'bitnami/kafka:latest'
    hostname: kafka
    env_file:
      - conf/kafka.config
    networks:
      - cluster-network

  kafka-producer:
    build:
      context: ./kafka-producer
      dockerfile: Dockerfile
    depends_on:
      - kafka
      - micro-challenger
    command: ["--apitoken", "sandro", "--name", "autoban", "--limit", "128"]
    env_file:
      - conf/kafka.client.config
    networks:
      - cluster-network

  kafka-ui:
    image: 'provectuslabs/kafka-ui:latest'
    hostname: kafka-ui
    depends_on:
      - kafka
    env_file:
      - conf/kafka.ui.config
    networks:
      - cluster-network

  spark-master:
    image: spark:latest
    container_name: spark-master
    hostname: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]
    volumes:
      - ./spark-target/spark-job.jar:/opt/app/app.jar
    environment:
      - SPARK_MODE=master
    networks:
      - cluster-network
    depends_on:
      - kafka
    tty: true

  spark-worker:
    image: spark:latest
    hostname: spark-worker
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]
    deploy:
      mode: replicated
      replicas: 3
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
    networks:
      - cluster-network

  firefox:
    image: jlesage/firefox
    ports:
      - 5800:5800
    networks:
      - cluster-network
